#!/usr/bin/env python3

#1

def q1_sum(l):
    total = 0
    for num_list in l:
        for num in num_list:
            if int(num) % 2 == 0:
                total += int(num)
    return total
            

##print(q1_sum([
#    [1, 0, 2],
#    [5, 5, 7],
#    [9, 4, 3]
#]))

#2


def move_vow(l):
    vowels = {"a":1,"e":1,"i":1,"o":1,"u":1}
    const_str = ""
    ans_str = ""
    for c in l:
        if c.lower() in vowels:
            ans_str += c
        else:
            const_str += c
    return ans_str + const_str


#print(move_vow('This is DCU!'))


#3

class Memories(object):
    def __init__(self, **abtributes):
        for k, v in abtributes.items():
            setattr(self, k, v)
    def remember(self, attr):
        if hasattr(self, attr):
            print(getattr(self, attr))
        else:
            return False
        

#person1 = Memories(name='Tom', age=32, salary=50000)
#print(person1.remember('salary'))
#print(person1.remember('email'))

#4

class Test(object):
    def __init__(self, subject_name, correct_answers, pasing_mark):
        self.subject_name = subject_name
        self.correct_answers = correct_answers
        self.pasing_mark = pasing_mark

class Student(object):
    def __init__(self, name):
        self.name = name
    def take_test(self, test, answers):
        i = 0
        ans_total = 0
        while i < len(answers):
            if answers[i] == test.correct_answers[i]:
                ans_total += 1
            i += 1
        ans_total = (ans_total * 100) // (i)
        if ans_total >= int(test.pasing_mark[:-1]):
            print(f'{self.name} passed the {test.subject_name} test with the score of {ans_total}%')
        else:
            print(f'{self.name} failed {test.subject_name} test!')

#paper1 = Test('Maths', ['1A', '2C', '3D', '4A', '5A'], '60%')
#paper2 = Test('Chemistry', ['1C', '2C', '3D', '4A'], '75%')
#paper3 = Test('Computing', ['1D', '2C', '3C', '4B', '5D', '6C', '7A'], '75%')
#stu1 = Student('Tom')
#stu1.take_test(paper2, ['1C', '2C', '3D', '4A'])

#stu2 = Student('John')
#stu2.take_test(paper1, ['1B', '2C', '3A', '4A', '5B'])


#5

def histogram(l, c):
    str = ""
    for num in l:
        print(c*num)

#histogram([6, 2, 15 , 3, 20 , 5], '=' )

#6 
def filter_star(d, num):
    for k, v in d.items():
        if len(v) == num:
            return f'{k}: {v}'
    return "No result found!"


#print(filter_star({
#  'Luxury Chocolates': '*****',
#  'Tasty Chocolates': '****',
#  'Big Chocolates': '*****',
#  'Generic Chocolates': '***'}, 4)
#)


#print(filter_star({
#  'Luxury Chocolates': '*****',
#  'Tasty Chocolates': '****',
#  'Big Chocolates': '*****',
#  'Generic Chocolates': '***'}, 2)
#)
